export const FOXMASK_THEME_APPEARANCE = 'FOXMASK_THEME_APPEARANCE';

export const FOXMASK_THEME_PRIMARY_COLOR = 'FOXMASK_THEME_PRIMARY_COLOR';

export const FOXMASK_THEME_NEUTRAL_COLOR = 'FOXMASK_THEME_NEUTRAL_COLOR';
